# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qFbRmJ5UiOv21Nw1aMvpUBHATb71H5MS
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Set the seaborn style
sns.set_theme(style="whitegrid")

h = 0.1
x = np.arange(0, 2*np.pi, h)
y = np.cos(x)

forward_diff = np.diff(y) / h
x_diff = x[:-1]

exact_solution = -np.sin(x_diff)

plt.figure(figsize=(12, 8))
plt.plot(x_diff, forward_diff, '--', label='Finite difference approximation')
plt.plot(x_diff, exact_solution, label='Exact solution')
plt.legend()
plt.show()

max_error = max(abs(exact_solution - forward_diff))
print(max_error)