# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qFbRmJ5UiOv21Nw1aMvpUBHATb71H5MS
"""

import numpy as np

x0 = 0.7
h = 2.0 ** -np.arange(1, 30)

df = (np.cos(x0 + h) - np.cos(x0)) / h
true_value = -np.sin(x0)

print("k | Approximation        | Ratio of errors   | Relative differences")
print("---|-----------------------|-------------------|----------------------")

previous_approximation = None
previous_error = None

for k in range(1, len(h) + 1):
    approximation = df[k - 1]
    error = np.abs(approximation - true_value)

    ratio = np.abs(previous_error / error) if previous_error is not None else " "
    relative_difference = (
        np.abs((approximation - previous_approximation) / previous_approximation)
        if previous_approximation is not None
        else " "
    )

    formatted_approximation = f"{approximation:.15f}"
    formatted_ratio = f"{ratio:.6f}" if isinstance(ratio, float) else ratio
    formatted_relative_difference = (
        f"{relative_difference:.10f}"
        if isinstance(relative_difference, float)
        else relative_difference
    )

    print(
        f"{k:<3}| {formatted_approximation:<21}| {formatted_ratio:<17}| {formatted_relative_difference:<20}"
    )

    previous_error = error
    previous_approximation = approximation

print(f"\nTrue value of the derivative: {true_value:.17f}")